/**
 * generated by Xtext
 */
package miso.carrascal.codeGenerator.serializer;

import miso.carrascal.codeGenerator.serializer.AbstractRulesSyntacticSequencer;

@SuppressWarnings("all")
public class RulesSyntacticSequencer extends AbstractRulesSyntacticSequencer {
}
