/*
 * generated by Xtext
 */
package miso.carrascal.codeGenerator.serializer;

import codeGeneratorModel.Artifact;
import codeGeneratorModel.CodeGeneratorModelPackage;
import codeGeneratorModel.Entity;
import codeGeneratorModel.MultiAttribute;
import codeGeneratorModel.MultiService;
import codeGeneratorModel.OnService;
import codeGeneratorModel.Root;
import codeGeneratorModel.SimpleAttribute;
import codeGeneratorModel.SimpleService;
import com.google.inject.Inject;
import com.google.inject.Provider;
import miso.carrascal.codeGenerator.services.RulesGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public abstract class AbstractRulesSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RulesGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == CodeGeneratorModelPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case CodeGeneratorModelPackage.ARTIFACT:
				sequence_Artifact(context, (Artifact) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.MULTI_ATTRIBUTE:
				sequence_MultiAttribute(context, (MultiAttribute) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.MULTI_SERVICE:
				sequence_MultiService(context, (MultiService) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.ON_SERVICE:
				sequence_OnService(context, (OnService) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.ROOT:
				sequence_Root(context, (Root) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.SIMPLE_ATTRIBUTE:
				sequence_SimpleAttribute(context, (SimpleAttribute) semanticObject); 
				return; 
			case CodeGeneratorModelPackage.SIMPLE_SERVICE:
				sequence_SimpleService(context, (SimpleService) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (name=EString (extension=EString? format=FormatEnum? (basicServices+=ServiceEnum basicServices+=ServiceEnum*)?)? attributes+=Attribute*)
	 */
	protected void sequence_Artifact(EObject context, Artifact semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=EString attributes+=Attribute*)
	 */
	protected void sequence_Entity(EObject context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=EString type=[Entity|EString])
	 */
	protected void sequence_MultiAttribute(EObject context, MultiAttribute semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, CodeGeneratorModelPackage.Literals.ATTRIBUTE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CodeGeneratorModelPackage.Literals.ATTRIBUTE__NAME));
			if(transientValues.isValueTransient(semanticObject, CodeGeneratorModelPackage.Literals.MULTI_ATTRIBUTE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CodeGeneratorModelPackage.Literals.MULTI_ATTRIBUTE__TYPE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getMultiAttributeAccess().getNameEStringParserRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getMultiAttributeAccess().getTypeEntityEStringParserRuleCall_2_0_1(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=EString parallel?='parallel'? when+=OnService* services+=[Service|EString] services+=[Service|EString]+)
	 */
	protected void sequence_MultiService(EObject context, MultiService semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (artifact=[Artifact|EString] whenServices+=ServiceEnum whenServices+=ServiceEnum*)
	 */
	protected void sequence_OnService(EObject context, OnService semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (artifacts+=Artifact (artifacts+=Artifact | entities+=Entity | services+=Service)*)
	 */
	protected void sequence_Root(EObject context, Root semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (many?='many'? required?='required'? name=EString data=DataEnum)
	 */
	protected void sequence_SimpleAttribute(EObject context, SimpleAttribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (input+=[AbstractEntity|EString] input+=[AbstractEntity|EString]*)? 
	 *         (output+=[AbstractEntity|EString] output+=[AbstractEntity|EString]*)? 
	 *         when+=OnService*
	 *     )
	 */
	protected void sequence_SimpleService(EObject context, SimpleService semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
}
