/*
 * generated by Xtext
 */
package miso.distil.codeGenerator;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RulesUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return miso.distil.codeGenerator.ui.internal.RulesActivator.getInstance().getInjector("miso.distil.codeGenerator.Rules");
	}
	
}
