/*
 * generated by Xtext
 */
package miso.distil.codeGenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RulesUiModule extends miso.distil.codeGenerator.ui.AbstractRulesUiModule {
	public RulesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
