/*
 * generated by Xtext
 */
package miso.carrascal.codeGenerator.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RulesGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Root");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cArtifactsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cArtifactsArtifactParserRuleCall_0_0 = (RuleCall)cArtifactsAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cArtifactsAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cArtifactsArtifactParserRuleCall_1_0_0 = (RuleCall)cArtifactsAssignment_1_0.eContents().get(0);
		private final Assignment cEntitiesAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cEntitiesEntityParserRuleCall_1_1_0 = (RuleCall)cEntitiesAssignment_1_1.eContents().get(0);
		private final Assignment cServicesAssignment_1_2 = (Assignment)cAlternatives_1.eContents().get(2);
		private final RuleCall cServicesServiceParserRuleCall_1_2_0 = (RuleCall)cServicesAssignment_1_2.eContents().get(0);
		
		//Root:
		//	artifacts+=Artifact (artifacts+=Artifact | entities+=Entity | services+=Service)*;
		@Override public ParserRule getRule() { return rule; }

		//artifacts+=Artifact (artifacts+=Artifact | entities+=Entity | services+=Service)*
		public Group getGroup() { return cGroup; }

		//artifacts+=Artifact
		public Assignment getArtifactsAssignment_0() { return cArtifactsAssignment_0; }

		//Artifact
		public RuleCall getArtifactsArtifactParserRuleCall_0_0() { return cArtifactsArtifactParserRuleCall_0_0; }

		//(artifacts+=Artifact | entities+=Entity | services+=Service)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//artifacts+=Artifact
		public Assignment getArtifactsAssignment_1_0() { return cArtifactsAssignment_1_0; }

		//Artifact
		public RuleCall getArtifactsArtifactParserRuleCall_1_0_0() { return cArtifactsArtifactParserRuleCall_1_0_0; }

		//entities+=Entity
		public Assignment getEntitiesAssignment_1_1() { return cEntitiesAssignment_1_1; }

		//Entity
		public RuleCall getEntitiesEntityParserRuleCall_1_1_0() { return cEntitiesEntityParserRuleCall_1_1_0; }

		//services+=Service
		public Assignment getServicesAssignment_1_2() { return cServicesAssignment_1_2; }

		//Service
		public RuleCall getServicesServiceParserRuleCall_1_2_0() { return cServicesServiceParserRuleCall_1_2_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class ServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Service");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSimpleServiceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMultiServiceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Service:
		//	SimpleService | MultiService;
		@Override public ParserRule getRule() { return rule; }

		//SimpleService | MultiService
		public Alternatives getAlternatives() { return cAlternatives; }

		//SimpleService
		public RuleCall getSimpleServiceParserRuleCall_0() { return cSimpleServiceParserRuleCall_0; }

		//MultiService
		public RuleCall getMultiServiceParserRuleCall_1() { return cMultiServiceParserRuleCall_1; }
	}

	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Attribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSimpleAttributeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMultiAttributeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Attribute:
		//	SimpleAttribute | MultiAttribute;
		@Override public ParserRule getRule() { return rule; }

		//SimpleAttribute | MultiAttribute
		public Alternatives getAlternatives() { return cAlternatives; }

		//SimpleAttribute
		public RuleCall getSimpleAttributeParserRuleCall_0() { return cSimpleAttributeParserRuleCall_0; }

		//MultiAttribute
		public RuleCall getMultiAttributeParserRuleCall_1() { return cMultiAttributeParserRuleCall_1; }
	}

	public class AbstractEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractEntity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cArtifactParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEntityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractEntity:
		//	Artifact | Entity;
		@Override public ParserRule getRule() { return rule; }

		//Artifact | Entity
		public Alternatives getAlternatives() { return cAlternatives; }

		//Artifact
		public RuleCall getArtifactParserRuleCall_0() { return cArtifactParserRuleCall_0; }

		//Entity
		public RuleCall getEntityParserRuleCall_1() { return cEntityParserRuleCall_1; }
	}

	public class ArtifactElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Artifact");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cArtifactAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cArtifactKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cExtensionKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cFullStopKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Assignment cExtensionAssignment_3_1_2 = (Assignment)cGroup_3_1.eContents().get(2);
		private final RuleCall cExtensionEStringParserRuleCall_3_1_2_0 = (RuleCall)cExtensionAssignment_3_1_2.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cFormatKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cFormatAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cFormatFormatEnumEnumRuleCall_3_2_1_0 = (RuleCall)cFormatAssignment_3_2_1.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cServicesKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cBasicServicesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cBasicServicesServiceEnumEnumRuleCall_3_3_1_0 = (RuleCall)cBasicServicesAssignment_3_3_1.eContents().get(0);
		private final Group cGroup_3_3_2 = (Group)cGroup_3_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_3_2_0 = (Keyword)cGroup_3_3_2.eContents().get(0);
		private final Assignment cBasicServicesAssignment_3_3_2_1 = (Assignment)cGroup_3_3_2.eContents().get(1);
		private final RuleCall cBasicServicesServiceEnumEnumRuleCall_3_3_2_1_0 = (RuleCall)cBasicServicesAssignment_3_3_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAttributesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAttributesAttributeParserRuleCall_5_0 = (RuleCall)cAttributesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Artifact:
		//	{Artifact} "Artifact" name=EString ("[" ("extension " "." extension=EString)? ("format " format=FormatEnum)?
		//	("services : " basicServices+=ServiceEnum ("," basicServices+=ServiceEnum)*)? "]")? "{" attributes+=Attribute* "}";
		@Override public ParserRule getRule() { return rule; }

		//{Artifact} "Artifact" name=EString ("[" ("extension " "." extension=EString)? ("format " format=FormatEnum)?
		//("services : " basicServices+=ServiceEnum ("," basicServices+=ServiceEnum)*)? "]")? "{" attributes+=Attribute* "}"
		public Group getGroup() { return cGroup; }

		//{Artifact}
		public Action getArtifactAction_0() { return cArtifactAction_0; }

		//"Artifact"
		public Keyword getArtifactKeyword_1() { return cArtifactKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//("[" ("extension " "." extension=EString)? ("format " format=FormatEnum)? ("services : " basicServices+=ServiceEnum (","
		//basicServices+=ServiceEnum)*)? "]")?
		public Group getGroup_3() { return cGroup_3; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3_0() { return cLeftSquareBracketKeyword_3_0; }

		//("extension " "." extension=EString)?
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"extension "
		public Keyword getExtensionKeyword_3_1_0() { return cExtensionKeyword_3_1_0; }

		//"."
		public Keyword getFullStopKeyword_3_1_1() { return cFullStopKeyword_3_1_1; }

		//extension=EString
		public Assignment getExtensionAssignment_3_1_2() { return cExtensionAssignment_3_1_2; }

		//EString
		public RuleCall getExtensionEStringParserRuleCall_3_1_2_0() { return cExtensionEStringParserRuleCall_3_1_2_0; }

		//("format " format=FormatEnum)?
		public Group getGroup_3_2() { return cGroup_3_2; }

		//"format "
		public Keyword getFormatKeyword_3_2_0() { return cFormatKeyword_3_2_0; }

		//format=FormatEnum
		public Assignment getFormatAssignment_3_2_1() { return cFormatAssignment_3_2_1; }

		//FormatEnum
		public RuleCall getFormatFormatEnumEnumRuleCall_3_2_1_0() { return cFormatFormatEnumEnumRuleCall_3_2_1_0; }

		//("services : " basicServices+=ServiceEnum ("," basicServices+=ServiceEnum)*)?
		public Group getGroup_3_3() { return cGroup_3_3; }

		//"services : "
		public Keyword getServicesKeyword_3_3_0() { return cServicesKeyword_3_3_0; }

		//basicServices+=ServiceEnum
		public Assignment getBasicServicesAssignment_3_3_1() { return cBasicServicesAssignment_3_3_1; }

		//ServiceEnum
		public RuleCall getBasicServicesServiceEnumEnumRuleCall_3_3_1_0() { return cBasicServicesServiceEnumEnumRuleCall_3_3_1_0; }

		//("," basicServices+=ServiceEnum)*
		public Group getGroup_3_3_2() { return cGroup_3_3_2; }

		//","
		public Keyword getCommaKeyword_3_3_2_0() { return cCommaKeyword_3_3_2_0; }

		//basicServices+=ServiceEnum
		public Assignment getBasicServicesAssignment_3_3_2_1() { return cBasicServicesAssignment_3_3_2_1; }

		//ServiceEnum
		public RuleCall getBasicServicesServiceEnumEnumRuleCall_3_3_2_1_0() { return cBasicServicesServiceEnumEnumRuleCall_3_3_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3_4() { return cRightSquareBracketKeyword_3_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//attributes+=Attribute*
		public Assignment getAttributesAssignment_5() { return cAttributesAssignment_5; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_5_0() { return cAttributesAttributeParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAttributesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAttributesAttributeParserRuleCall_4_0 = (RuleCall)cAttributesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Entity:
		//	{Entity} "Entity" name=EString "{" attributes+=Attribute* "}";
		@Override public ParserRule getRule() { return rule; }

		//{Entity} "Entity" name=EString "{" attributes+=Attribute* "}"
		public Group getGroup() { return cGroup; }

		//{Entity}
		public Action getEntityAction_0() { return cEntityAction_0; }

		//"Entity"
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//attributes+=Attribute*
		public Assignment getAttributesAssignment_4() { return cAttributesAssignment_4; }

		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_4_0() { return cAttributesAttributeParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class SimpleAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cManyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cManyManyKeyword_0_0 = (Keyword)cManyAssignment_0.eContents().get(0);
		private final Assignment cRequiredAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cRequiredRequiredKeyword_1_0 = (Keyword)cRequiredAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDataAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDataDataEnumEnumRuleCall_4_0 = (RuleCall)cDataAssignment_4.eContents().get(0);
		
		//SimpleAttribute:
		//	many?="many"? required?="required"? name=EString ":" data=DataEnum;
		@Override public ParserRule getRule() { return rule; }

		//many?="many"? required?="required"? name=EString ":" data=DataEnum
		public Group getGroup() { return cGroup; }

		//many?="many"?
		public Assignment getManyAssignment_0() { return cManyAssignment_0; }

		//"many"
		public Keyword getManyManyKeyword_0_0() { return cManyManyKeyword_0_0; }

		//required?="required"?
		public Assignment getRequiredAssignment_1() { return cRequiredAssignment_1; }

		//"required"
		public Keyword getRequiredRequiredKeyword_1_0() { return cRequiredRequiredKeyword_1_0; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//data=DataEnum
		public Assignment getDataAssignment_4() { return cDataAssignment_4; }

		//DataEnum
		public RuleCall getDataDataEnumEnumRuleCall_4_0() { return cDataDataEnumEnumRuleCall_4_0; }
	}

	public class MultiAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultiAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeEntityCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeEntityEStringParserRuleCall_2_0_1 = (RuleCall)cTypeEntityCrossReference_2_0.eContents().get(1);
		
		//MultiAttribute:
		//	name=EString ":" type=[Entity|EString];
		@Override public ParserRule getRule() { return rule; }

		//name=EString ":" type=[Entity|EString]
		public Group getGroup() { return cGroup; }

		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//type=[Entity|EString]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }

		//[Entity|EString]
		public CrossReference getTypeEntityCrossReference_2_0() { return cTypeEntityCrossReference_2_0; }

		//EString
		public RuleCall getTypeEntityEStringParserRuleCall_2_0_1() { return cTypeEntityEStringParserRuleCall_2_0_1; }
	}

	public class OnServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OnService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cArtifactAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cArtifactArtifactCrossReference_0_0 = (CrossReference)cArtifactAssignment_0.eContents().get(0);
		private final RuleCall cArtifactArtifactEStringParserRuleCall_0_0_1 = (RuleCall)cArtifactArtifactCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cWhenServicesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cWhenServicesServiceEnumEnumRuleCall_2_0 = (RuleCall)cWhenServicesAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cWhenServicesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cWhenServicesServiceEnumEnumRuleCall_3_1_0 = (RuleCall)cWhenServicesAssignment_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//OnService:
		//	artifact=[Artifact|EString] "[" whenServices+=ServiceEnum ("," whenServices+=ServiceEnum)* "]";
		@Override public ParserRule getRule() { return rule; }

		//artifact=[Artifact|EString] "[" whenServices+=ServiceEnum ("," whenServices+=ServiceEnum)* "]"
		public Group getGroup() { return cGroup; }

		//artifact=[Artifact|EString]
		public Assignment getArtifactAssignment_0() { return cArtifactAssignment_0; }

		//[Artifact|EString]
		public CrossReference getArtifactArtifactCrossReference_0_0() { return cArtifactArtifactCrossReference_0_0; }

		//EString
		public RuleCall getArtifactArtifactEStringParserRuleCall_0_0_1() { return cArtifactArtifactEStringParserRuleCall_0_0_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//whenServices+=ServiceEnum
		public Assignment getWhenServicesAssignment_2() { return cWhenServicesAssignment_2; }

		//ServiceEnum
		public RuleCall getWhenServicesServiceEnumEnumRuleCall_2_0() { return cWhenServicesServiceEnumEnumRuleCall_2_0; }

		//("," whenServices+=ServiceEnum)*
		public Group getGroup_3() { return cGroup_3; }

		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }

		//whenServices+=ServiceEnum
		public Assignment getWhenServicesAssignment_3_1() { return cWhenServicesAssignment_3_1; }

		//ServiceEnum
		public RuleCall getWhenServicesServiceEnumEnumRuleCall_3_1_0() { return cWhenServicesServiceEnumEnumRuleCall_3_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}

	public class SimpleServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInputKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInputAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cInputAbstractEntityCrossReference_3_1_0 = (CrossReference)cInputAssignment_3_1.eContents().get(0);
		private final RuleCall cInputAbstractEntityEStringParserRuleCall_3_1_0_1 = (RuleCall)cInputAbstractEntityCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cInputAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final CrossReference cInputAbstractEntityCrossReference_3_2_1_0 = (CrossReference)cInputAssignment_3_2_1.eContents().get(0);
		private final RuleCall cInputAbstractEntityEStringParserRuleCall_3_2_1_0_1 = (RuleCall)cInputAbstractEntityCrossReference_3_2_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOutputKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOutputAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cOutputAbstractEntityCrossReference_4_1_0 = (CrossReference)cOutputAssignment_4_1.eContents().get(0);
		private final RuleCall cOutputAbstractEntityEStringParserRuleCall_4_1_0_1 = (RuleCall)cOutputAbstractEntityCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Keyword cCommaKeyword_4_2_0 = (Keyword)cGroup_4_2.eContents().get(0);
		private final Assignment cOutputAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final CrossReference cOutputAbstractEntityCrossReference_4_2_1_0 = (CrossReference)cOutputAssignment_4_2_1.eContents().get(0);
		private final RuleCall cOutputAbstractEntityEStringParserRuleCall_4_2_1_0_1 = (RuleCall)cOutputAbstractEntityCrossReference_4_2_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWhenKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cWhenAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cWhenOnServiceParserRuleCall_5_1_0 = (RuleCall)cWhenAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SimpleService:
		//	"Service" name=EString "{" ("input : " input+=[AbstractEntity|EString] ("," input+=[AbstractEntity|EString])*)?
		//	("output : " output+=[AbstractEntity|EString] ("," output+=[AbstractEntity|EString])*)? ("when : " when+=OnService)*
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"Service" name=EString "{" ("input : " input+=[AbstractEntity|EString] ("," input+=[AbstractEntity|EString])*)?
		//("output : " output+=[AbstractEntity|EString] ("," output+=[AbstractEntity|EString])*)? ("when : " when+=OnService)*
		//"}"
		public Group getGroup() { return cGroup; }

		//"Service"
		public Keyword getServiceKeyword_0() { return cServiceKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("input : " input+=[AbstractEntity|EString] ("," input+=[AbstractEntity|EString])*)?
		public Group getGroup_3() { return cGroup_3; }

		//"input : "
		public Keyword getInputKeyword_3_0() { return cInputKeyword_3_0; }

		//input+=[AbstractEntity|EString]
		public Assignment getInputAssignment_3_1() { return cInputAssignment_3_1; }

		//[AbstractEntity|EString]
		public CrossReference getInputAbstractEntityCrossReference_3_1_0() { return cInputAbstractEntityCrossReference_3_1_0; }

		//EString
		public RuleCall getInputAbstractEntityEStringParserRuleCall_3_1_0_1() { return cInputAbstractEntityEStringParserRuleCall_3_1_0_1; }

		//("," input+=[AbstractEntity|EString])*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//input+=[AbstractEntity|EString]
		public Assignment getInputAssignment_3_2_1() { return cInputAssignment_3_2_1; }

		//[AbstractEntity|EString]
		public CrossReference getInputAbstractEntityCrossReference_3_2_1_0() { return cInputAbstractEntityCrossReference_3_2_1_0; }

		//EString
		public RuleCall getInputAbstractEntityEStringParserRuleCall_3_2_1_0_1() { return cInputAbstractEntityEStringParserRuleCall_3_2_1_0_1; }

		//("output : " output+=[AbstractEntity|EString] ("," output+=[AbstractEntity|EString])*)?
		public Group getGroup_4() { return cGroup_4; }

		//"output : "
		public Keyword getOutputKeyword_4_0() { return cOutputKeyword_4_0; }

		//output+=[AbstractEntity|EString]
		public Assignment getOutputAssignment_4_1() { return cOutputAssignment_4_1; }

		//[AbstractEntity|EString]
		public CrossReference getOutputAbstractEntityCrossReference_4_1_0() { return cOutputAbstractEntityCrossReference_4_1_0; }

		//EString
		public RuleCall getOutputAbstractEntityEStringParserRuleCall_4_1_0_1() { return cOutputAbstractEntityEStringParserRuleCall_4_1_0_1; }

		//("," output+=[AbstractEntity|EString])*
		public Group getGroup_4_2() { return cGroup_4_2; }

		//","
		public Keyword getCommaKeyword_4_2_0() { return cCommaKeyword_4_2_0; }

		//output+=[AbstractEntity|EString]
		public Assignment getOutputAssignment_4_2_1() { return cOutputAssignment_4_2_1; }

		//[AbstractEntity|EString]
		public CrossReference getOutputAbstractEntityCrossReference_4_2_1_0() { return cOutputAbstractEntityCrossReference_4_2_1_0; }

		//EString
		public RuleCall getOutputAbstractEntityEStringParserRuleCall_4_2_1_0_1() { return cOutputAbstractEntityEStringParserRuleCall_4_2_1_0_1; }

		//("when : " when+=OnService)*
		public Group getGroup_5() { return cGroup_5; }

		//"when : "
		public Keyword getWhenKeyword_5_0() { return cWhenKeyword_5_0; }

		//when+=OnService
		public Assignment getWhenAssignment_5_1() { return cWhenAssignment_5_1; }

		//OnService
		public RuleCall getWhenOnServiceParserRuleCall_5_1_0() { return cWhenOnServiceParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class MultiServiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultiService");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMultiServiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cParallelAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final Keyword cParallelParallelKeyword_2_1_0 = (Keyword)cParallelAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWhenKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cWhenAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cWhenOnServiceParserRuleCall_4_1_0 = (RuleCall)cWhenAssignment_4_1.eContents().get(0);
		private final Keyword cServicesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cServicesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cServicesServiceCrossReference_6_0 = (CrossReference)cServicesAssignment_6.eContents().get(0);
		private final RuleCall cServicesServiceEStringParserRuleCall_6_0_1 = (RuleCall)cServicesServiceCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cServicesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cServicesServiceCrossReference_7_1_0 = (CrossReference)cServicesAssignment_7_1.eContents().get(0);
		private final RuleCall cServicesServiceEStringParserRuleCall_7_1_0_1 = (RuleCall)cServicesServiceCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//MultiService:
		//	"MultiService" name=EString ("[" parallel?="parallel"? "]")? "{" ("when : " when+=OnService)* "services : "
		//	services+=[Service|EString] ("," services+=[Service|EString])+ "}";
		@Override public ParserRule getRule() { return rule; }

		//"MultiService" name=EString ("[" parallel?="parallel"? "]")? "{" ("when : " when+=OnService)* "services : "
		//services+=[Service|EString] ("," services+=[Service|EString])+ "}"
		public Group getGroup() { return cGroup; }

		//"MultiService"
		public Keyword getMultiServiceKeyword_0() { return cMultiServiceKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//("[" parallel?="parallel"? "]")?
		public Group getGroup_2() { return cGroup_2; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }

		//parallel?="parallel"?
		public Assignment getParallelAssignment_2_1() { return cParallelAssignment_2_1; }

		//"parallel"
		public Keyword getParallelParallelKeyword_2_1_0() { return cParallelParallelKeyword_2_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("when : " when+=OnService)*
		public Group getGroup_4() { return cGroup_4; }

		//"when : "
		public Keyword getWhenKeyword_4_0() { return cWhenKeyword_4_0; }

		//when+=OnService
		public Assignment getWhenAssignment_4_1() { return cWhenAssignment_4_1; }

		//OnService
		public RuleCall getWhenOnServiceParserRuleCall_4_1_0() { return cWhenOnServiceParserRuleCall_4_1_0; }

		//"services : "
		public Keyword getServicesKeyword_5() { return cServicesKeyword_5; }

		//services+=[Service|EString]
		public Assignment getServicesAssignment_6() { return cServicesAssignment_6; }

		//[Service|EString]
		public CrossReference getServicesServiceCrossReference_6_0() { return cServicesServiceCrossReference_6_0; }

		//EString
		public RuleCall getServicesServiceEStringParserRuleCall_6_0_1() { return cServicesServiceEStringParserRuleCall_6_0_1; }

		//("," services+=[Service|EString])+
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//services+=[Service|EString]
		public Assignment getServicesAssignment_7_1() { return cServicesAssignment_7_1; }

		//[Service|EString]
		public CrossReference getServicesServiceCrossReference_7_1_0() { return cServicesServiceCrossReference_7_1_0; }

		//EString
		public RuleCall getServicesServiceEStringParserRuleCall_7_1_0_1() { return cServicesServiceEStringParserRuleCall_7_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	public class FormatEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "FormatEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cXMIEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cXMIXMIKeyword_0_0 = (Keyword)cXMIEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBINARYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBINARYBINARYKeyword_1_0 = (Keyword)cBINARYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTEXTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTEXTTEXTKeyword_2_0 = (Keyword)cTEXTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cXMLEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cXMLXMLKeyword_3_0 = (Keyword)cXMLEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cJSONEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cJSONJSONKeyword_4_0 = (Keyword)cJSONEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cATLEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cATLATLKeyword_5_0 = (Keyword)cATLEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cZIPEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cZIPZIPKeyword_6_0 = (Keyword)cZIPEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum FormatEnum:
		//	XMI | BINARY | TEXT | XML | JSON | ATL | ZIP;
		public EnumRule getRule() { return rule; }

		//XMI | BINARY | TEXT | XML | JSON | ATL | ZIP
		public Alternatives getAlternatives() { return cAlternatives; }

		//XMI
		public EnumLiteralDeclaration getXMIEnumLiteralDeclaration_0() { return cXMIEnumLiteralDeclaration_0; }

		//"XMI"
		public Keyword getXMIXMIKeyword_0_0() { return cXMIXMIKeyword_0_0; }

		//BINARY
		public EnumLiteralDeclaration getBINARYEnumLiteralDeclaration_1() { return cBINARYEnumLiteralDeclaration_1; }

		//"BINARY"
		public Keyword getBINARYBINARYKeyword_1_0() { return cBINARYBINARYKeyword_1_0; }

		//TEXT
		public EnumLiteralDeclaration getTEXTEnumLiteralDeclaration_2() { return cTEXTEnumLiteralDeclaration_2; }

		//"TEXT"
		public Keyword getTEXTTEXTKeyword_2_0() { return cTEXTTEXTKeyword_2_0; }

		//XML
		public EnumLiteralDeclaration getXMLEnumLiteralDeclaration_3() { return cXMLEnumLiteralDeclaration_3; }

		//"XML"
		public Keyword getXMLXMLKeyword_3_0() { return cXMLXMLKeyword_3_0; }

		//JSON
		public EnumLiteralDeclaration getJSONEnumLiteralDeclaration_4() { return cJSONEnumLiteralDeclaration_4; }

		//"JSON"
		public Keyword getJSONJSONKeyword_4_0() { return cJSONJSONKeyword_4_0; }

		//ATL
		public EnumLiteralDeclaration getATLEnumLiteralDeclaration_5() { return cATLEnumLiteralDeclaration_5; }

		//"ATL"
		public Keyword getATLATLKeyword_5_0() { return cATLATLKeyword_5_0; }

		//ZIP
		public EnumLiteralDeclaration getZIPEnumLiteralDeclaration_6() { return cZIPEnumLiteralDeclaration_6; }

		//"ZIP"
		public Keyword getZIPZIPKeyword_6_0() { return cZIPZIPKeyword_6_0; }
	}

	public class ServiceEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ServiceEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUploadEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUploadUploadKeyword_0_0 = (Keyword)cUploadEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDownloadEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDownloadDownloadKeyword_1_0 = (Keyword)cDownloadEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cUpdateEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cUpdateUpdateKeyword_2_0 = (Keyword)cUpdateEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cReadEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cReadReadKeyword_3_0 = (Keyword)cReadEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cReadAllEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cReadAllReadAllKeyword_4_0 = (Keyword)cReadAllEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSearchEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSearchSearchKeyword_5_0 = (Keyword)cSearchEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum ServiceEnum:
		//	upload | download | update | read | readAll | search;
		public EnumRule getRule() { return rule; }

		//upload | download | update | read | readAll | search
		public Alternatives getAlternatives() { return cAlternatives; }

		//upload
		public EnumLiteralDeclaration getUploadEnumLiteralDeclaration_0() { return cUploadEnumLiteralDeclaration_0; }

		//"upload"
		public Keyword getUploadUploadKeyword_0_0() { return cUploadUploadKeyword_0_0; }

		//download
		public EnumLiteralDeclaration getDownloadEnumLiteralDeclaration_1() { return cDownloadEnumLiteralDeclaration_1; }

		//"download"
		public Keyword getDownloadDownloadKeyword_1_0() { return cDownloadDownloadKeyword_1_0; }

		//update
		public EnumLiteralDeclaration getUpdateEnumLiteralDeclaration_2() { return cUpdateEnumLiteralDeclaration_2; }

		//"update"
		public Keyword getUpdateUpdateKeyword_2_0() { return cUpdateUpdateKeyword_2_0; }

		//read
		public EnumLiteralDeclaration getReadEnumLiteralDeclaration_3() { return cReadEnumLiteralDeclaration_3; }

		//"read"
		public Keyword getReadReadKeyword_3_0() { return cReadReadKeyword_3_0; }

		//readAll
		public EnumLiteralDeclaration getReadAllEnumLiteralDeclaration_4() { return cReadAllEnumLiteralDeclaration_4; }

		//"readAll"
		public Keyword getReadAllReadAllKeyword_4_0() { return cReadAllReadAllKeyword_4_0; }

		//search
		public EnumLiteralDeclaration getSearchEnumLiteralDeclaration_5() { return cSearchEnumLiteralDeclaration_5; }

		//"search"
		public Keyword getSearchSearchKeyword_5_0() { return cSearchSearchKeyword_5_0; }
	}

	public class DataEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "DataEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBooleanBooleanKeyword_0_0 = (Keyword)cBooleanEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDoubleDoubleKeyword_1_0 = (Keyword)cDoubleEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cIntegerEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cIntegerIntegerKeyword_2_0 = (Keyword)cIntegerEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cStringStringKeyword_3_0 = (Keyword)cStringEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum DataEnum:
		//	Boolean | Double | Integer | String;
		public EnumRule getRule() { return rule; }

		//Boolean | Double | Integer | String
		public Alternatives getAlternatives() { return cAlternatives; }

		//Boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_0() { return cBooleanEnumLiteralDeclaration_0; }

		//"Boolean"
		public Keyword getBooleanBooleanKeyword_0_0() { return cBooleanBooleanKeyword_0_0; }

		//Double
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_1() { return cDoubleEnumLiteralDeclaration_1; }

		//"Double"
		public Keyword getDoubleDoubleKeyword_1_0() { return cDoubleDoubleKeyword_1_0; }

		//Integer
		public EnumLiteralDeclaration getIntegerEnumLiteralDeclaration_2() { return cIntegerEnumLiteralDeclaration_2; }

		//"Integer"
		public Keyword getIntegerIntegerKeyword_2_0() { return cIntegerIntegerKeyword_2_0; }

		//String
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_3() { return cStringEnumLiteralDeclaration_3; }

		//"String"
		public Keyword getStringStringKeyword_3_0() { return cStringStringKeyword_3_0; }
	}
	
	private final RootElements pRoot;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final ServiceElements pService;
	private final AttributeElements pAttribute;
	private final AbstractEntityElements pAbstractEntity;
	private final FormatEnumElements unknownRuleFormatEnum;
	private final ServiceEnumElements unknownRuleServiceEnum;
	private final DataEnumElements unknownRuleDataEnum;
	private final ArtifactElements pArtifact;
	private final EntityElements pEntity;
	private final SimpleAttributeElements pSimpleAttribute;
	private final MultiAttributeElements pMultiAttribute;
	private final OnServiceElements pOnService;
	private final SimpleServiceElements pSimpleService;
	private final MultiServiceElements pMultiService;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RulesGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRoot = new RootElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.pService = new ServiceElements();
		this.pAttribute = new AttributeElements();
		this.pAbstractEntity = new AbstractEntityElements();
		this.unknownRuleFormatEnum = new FormatEnumElements();
		this.unknownRuleServiceEnum = new ServiceEnumElements();
		this.unknownRuleDataEnum = new DataEnumElements();
		this.pArtifact = new ArtifactElements();
		this.pEntity = new EntityElements();
		this.pSimpleAttribute = new SimpleAttributeElements();
		this.pMultiAttribute = new MultiAttributeElements();
		this.pOnService = new OnServiceElements();
		this.pSimpleService = new SimpleServiceElements();
		this.pMultiService = new MultiServiceElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("miso.carrascal.codeGenerator.Rules".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Root:
	//	artifacts+=Artifact (artifacts+=Artifact | entities+=Entity | services+=Service)*;
	public RootElements getRootAccess() {
		return pRoot;
	}
	
	public ParserRule getRootRule() {
		return getRootAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//Service:
	//	SimpleService | MultiService;
	public ServiceElements getServiceAccess() {
		return pService;
	}
	
	public ParserRule getServiceRule() {
		return getServiceAccess().getRule();
	}

	//Attribute:
	//	SimpleAttribute | MultiAttribute;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}

	//AbstractEntity:
	//	Artifact | Entity;
	public AbstractEntityElements getAbstractEntityAccess() {
		return pAbstractEntity;
	}
	
	public ParserRule getAbstractEntityRule() {
		return getAbstractEntityAccess().getRule();
	}

	//enum FormatEnum:
	//	XMI | BINARY | TEXT | XML | JSON | ATL | ZIP;
	public FormatEnumElements getFormatEnumAccess() {
		return unknownRuleFormatEnum;
	}
	
	public EnumRule getFormatEnumRule() {
		return getFormatEnumAccess().getRule();
	}

	//enum ServiceEnum:
	//	upload | download | update | read | readAll | search;
	public ServiceEnumElements getServiceEnumAccess() {
		return unknownRuleServiceEnum;
	}
	
	public EnumRule getServiceEnumRule() {
		return getServiceEnumAccess().getRule();
	}

	//enum DataEnum:
	//	Boolean | Double | Integer | String;
	public DataEnumElements getDataEnumAccess() {
		return unknownRuleDataEnum;
	}
	
	public EnumRule getDataEnumRule() {
		return getDataEnumAccess().getRule();
	}

	//Artifact:
	//	{Artifact} "Artifact" name=EString ("[" ("extension " "." extension=EString)? ("format " format=FormatEnum)?
	//	("services : " basicServices+=ServiceEnum ("," basicServices+=ServiceEnum)*)? "]")? "{" attributes+=Attribute* "}";
	public ArtifactElements getArtifactAccess() {
		return pArtifact;
	}
	
	public ParserRule getArtifactRule() {
		return getArtifactAccess().getRule();
	}

	//Entity:
	//	{Entity} "Entity" name=EString "{" attributes+=Attribute* "}";
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}

	//SimpleAttribute:
	//	many?="many"? required?="required"? name=EString ":" data=DataEnum;
	public SimpleAttributeElements getSimpleAttributeAccess() {
		return pSimpleAttribute;
	}
	
	public ParserRule getSimpleAttributeRule() {
		return getSimpleAttributeAccess().getRule();
	}

	//MultiAttribute:
	//	name=EString ":" type=[Entity|EString];
	public MultiAttributeElements getMultiAttributeAccess() {
		return pMultiAttribute;
	}
	
	public ParserRule getMultiAttributeRule() {
		return getMultiAttributeAccess().getRule();
	}

	//OnService:
	//	artifact=[Artifact|EString] "[" whenServices+=ServiceEnum ("," whenServices+=ServiceEnum)* "]";
	public OnServiceElements getOnServiceAccess() {
		return pOnService;
	}
	
	public ParserRule getOnServiceRule() {
		return getOnServiceAccess().getRule();
	}

	//SimpleService:
	//	"Service" name=EString "{" ("input : " input+=[AbstractEntity|EString] ("," input+=[AbstractEntity|EString])*)?
	//	("output : " output+=[AbstractEntity|EString] ("," output+=[AbstractEntity|EString])*)? ("when : " when+=OnService)*
	//	"}";
	public SimpleServiceElements getSimpleServiceAccess() {
		return pSimpleService;
	}
	
	public ParserRule getSimpleServiceRule() {
		return getSimpleServiceAccess().getRule();
	}

	//MultiService:
	//	"MultiService" name=EString ("[" parallel?="parallel"? "]")? "{" ("when : " when+=OnService)* "services : "
	//	services+=[Service|EString] ("," services+=[Service|EString])+ "}";
	public MultiServiceElements getMultiServiceAccess() {
		return pMultiService;
	}
	
	public ParserRule getMultiServiceRule() {
		return getMultiServiceAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
