package miso.distil.codeGenerator.generator.custom;

import com.google.inject.Inject;
import miso.distil.codeGenerator.generator.Names;
import miso.distil.codeGenerator.generator.generateUtils;

/**
 * To write XXXJson.java.
 * 
 * @author Carlos Carrascal.
 */
@SuppressWarnings("all")
public class generateJson {
  @Inject
  private generateUtils genUti;
  
  @Inject
  private Names names;
  
  /**
   * To write "artifact.name"Json.java.
   * 
   * @param artifact the artifact.
   */
  public CharSequence write(final /* Artifact */Object artifact) {
    throw new Error("Unresolved compilation problems:"
      + "\nServiceEnum cannot be resolved to a type."
      + "\nAttribute cannot be resolved to a type."
      + "\nAttribute cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nArtifactID cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nArtifactID cannot be resolved to a type."
      + "\nReference cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nPrimitive cannot be resolved to a type."
      + "\nArtifactID cannot be resolved to a type."
      + "\nReference cannot be resolved to a type."
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field ServiceEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nThe method or field DataEnum is undefined for the type generateJson"
      + "\nbasicServices cannot be resolved"
      + "\nattributes cannot be resolved"
      + "\nattributes cannot be resolved"
      + "\nname cannot be resolved"
      + "\ntoLowerCase cannot be resolved"
      + "\nname cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nUPDATE cannot be resolved"
      + "\nUPDATE cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nUPDATE cannot be resolved"
      + "\nmany cannot be resolved"
      + "\nmany cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nUPDATE cannot be resolved"
      + "\nrequired cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nUPDATE cannot be resolved"
      + "\nUPDATE cannot be resolved"
      + "\nrequired cannot be resolved"
      + "\nrequired cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nSTRING cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nINTEGER cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nDOUBLE cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nBOOLEAN cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nSTRING cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nINTEGER cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nDOUBLE cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nBOOLEAN cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\nrequired cannot be resolved"
      + "\n! cannot be resolved"
      + "\nUPLOAD cannot be resolved"
      + "\nrequired cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nBOOLEAN cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nINTEGER cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nDOUBLE cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nSTRING cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nmany cannot be resolved"
      + "\n! cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nINTEGER cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nDOUBLE cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nSTRING cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\ntype cannot be resolved"
      + "\nequals cannot be resolved"
      + "\nBOOLEAN cannot be resolved"
      + "\ntoFirstUpper cannot be resolved"
      + "\nextension cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nextension cannot be resolved"
      + "\nrequired cannot be resolved"
      + "\n! cannot be resolved");
  }
}
