/*
 * generated by Xtext
 */
package miso.distil.codeGenerator.ui.contentassist

import miso.distil.codeGenerator.ui.contentassist.AbstractRulesProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RulesProposalProvider extends AbstractRulesProposalProvider {
}
