/**
 * generated by Xtext
 */
package miso.distil.codeGenerator.serializer;

import miso.distil.codeGenerator.serializer.AbstractRulesSemanticSequencer;

@SuppressWarnings("all")
public class RulesSemanticSequencer extends AbstractRulesSemanticSequencer {
}
