/**
 * generated by Xtext
 */
package miso.distil.codeGenerator.serializer;

import miso.distil.codeGenerator.serializer.AbstractRulesSyntacticSequencer;

@SuppressWarnings("all")
public class RulesSyntacticSequencer extends AbstractRulesSyntacticSequencer {
}
