/*
 * generated by Xtext
 */
package miso.distil.codeGenerator.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import miso.distil.codeGenerator.services.RulesGrammarAccess;

public class RulesParser extends AbstractContentAssistParser {
	
	@Inject
	private RulesGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected miso.distil.codeGenerator.ui.contentassist.antlr.internal.InternalRulesParser createParser() {
		miso.distil.codeGenerator.ui.contentassist.antlr.internal.InternalRulesParser result = new miso.distil.codeGenerator.ui.contentassist.antlr.internal.InternalRulesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRootAccess().getAlternatives_2(), "rule__Root__Alternatives_2");
					put(grammarAccess.getServiceAccess().getAlternatives(), "rule__Service__Alternatives");
					put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
					put(grammarAccess.getAbstractEntityAccess().getAlternatives(), "rule__AbstractEntity__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getFormatEnumAccess().getAlternatives(), "rule__FormatEnum__Alternatives");
					put(grammarAccess.getServiceEnumAccess().getAlternatives(), "rule__ServiceEnum__Alternatives");
					put(grammarAccess.getDataEnumAccess().getAlternatives(), "rule__DataEnum__Alternatives");
					put(grammarAccess.getRootAccess().getGroup(), "rule__Root__Group__0");
					put(grammarAccess.getRootAccess().getGroup_0(), "rule__Root__Group_0__0");
					put(grammarAccess.getArtifactAccess().getGroup(), "rule__Artifact__Group__0");
					put(grammarAccess.getArtifactAccess().getGroup_2(), "rule__Artifact__Group_2__0");
					put(grammarAccess.getArtifactAccess().getGroup_2_1(), "rule__Artifact__Group_2_1__0");
					put(grammarAccess.getArtifactAccess().getGroup_2_2(), "rule__Artifact__Group_2_2__0");
					put(grammarAccess.getArtifactAccess().getGroup_2_3(), "rule__Artifact__Group_2_3__0");
					put(grammarAccess.getArtifactAccess().getGroup_2_3_2(), "rule__Artifact__Group_2_3_2__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getPrimitiveAccess().getGroup(), "rule__Primitive__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getArtifactIDAccess().getGroup(), "rule__ArtifactID__Group__0");
					put(grammarAccess.getOnServiceAccess().getGroup(), "rule__OnService__Group__0");
					put(grammarAccess.getOnServiceAccess().getGroup_3(), "rule__OnService__Group_3__0");
					put(grammarAccess.getSimpleServiceAccess().getGroup(), "rule__SimpleService__Group__0");
					put(grammarAccess.getSimpleServiceAccess().getGroup_4(), "rule__SimpleService__Group_4__0");
					put(grammarAccess.getSimpleServiceAccess().getGroup_4_2(), "rule__SimpleService__Group_4_2__0");
					put(grammarAccess.getSimpleServiceAccess().getGroup_5(), "rule__SimpleService__Group_5__0");
					put(grammarAccess.getSimpleServiceAccess().getGroup_5_2(), "rule__SimpleService__Group_5_2__0");
					put(grammarAccess.getSimpleServiceAccess().getGroup_6(), "rule__SimpleService__Group_6__0");
					put(grammarAccess.getMultiServiceAccess().getGroup(), "rule__MultiService__Group__0");
					put(grammarAccess.getMultiServiceAccess().getGroup_2(), "rule__MultiService__Group_2__0");
					put(grammarAccess.getMultiServiceAccess().getGroup_4(), "rule__MultiService__Group_4__0");
					put(grammarAccess.getMultiServiceAccess().getGroup_7(), "rule__MultiService__Group_7__0");
					put(grammarAccess.getInoutAccess().getGroup(), "rule__Inout__Group__0");
					put(grammarAccess.getInoutAccess().getGroup_2(), "rule__Inout__Group_2__0");
					put(grammarAccess.getCompAccess().getGroup(), "rule__Comp__Group__0");
					put(grammarAccess.getCompAccess().getGroup_1(), "rule__Comp__Group_1__0");
					put(grammarAccess.getRootAccess().getMongoURIsAssignment_0_2(), "rule__Root__MongoURIsAssignment_0_2");
					put(grammarAccess.getRootAccess().getArtifactsAssignment_1(), "rule__Root__ArtifactsAssignment_1");
					put(grammarAccess.getRootAccess().getArtifactsAssignment_2_0(), "rule__Root__ArtifactsAssignment_2_0");
					put(grammarAccess.getRootAccess().getEntitiesAssignment_2_1(), "rule__Root__EntitiesAssignment_2_1");
					put(grammarAccess.getRootAccess().getServicesAssignment_2_2(), "rule__Root__ServicesAssignment_2_2");
					put(grammarAccess.getArtifactAccess().getNameAssignment_1(), "rule__Artifact__NameAssignment_1");
					put(grammarAccess.getArtifactAccess().getExtensionAssignment_2_1_2(), "rule__Artifact__ExtensionAssignment_2_1_2");
					put(grammarAccess.getArtifactAccess().getFormatAssignment_2_2_1(), "rule__Artifact__FormatAssignment_2_2_1");
					put(grammarAccess.getArtifactAccess().getBasicServicesAssignment_2_3_1(), "rule__Artifact__BasicServicesAssignment_2_3_1");
					put(grammarAccess.getArtifactAccess().getBasicServicesAssignment_2_3_2_1(), "rule__Artifact__BasicServicesAssignment_2_3_2_1");
					put(grammarAccess.getArtifactAccess().getAttributesAssignment_4(), "rule__Artifact__AttributesAssignment_4");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_3(), "rule__Entity__AttributesAssignment_3");
					put(grammarAccess.getPrimitiveAccess().getManyAssignment_0(), "rule__Primitive__ManyAssignment_0");
					put(grammarAccess.getPrimitiveAccess().getRequiredAssignment_1(), "rule__Primitive__RequiredAssignment_1");
					put(grammarAccess.getPrimitiveAccess().getNameAssignment_2(), "rule__Primitive__NameAssignment_2");
					put(grammarAccess.getPrimitiveAccess().getTypeAssignment_4(), "rule__Primitive__TypeAssignment_4");
					put(grammarAccess.getReferenceAccess().getManyAssignment_1(), "rule__Reference__ManyAssignment_1");
					put(grammarAccess.getReferenceAccess().getNameAssignment_2(), "rule__Reference__NameAssignment_2");
					put(grammarAccess.getReferenceAccess().getTypeAssignment_4(), "rule__Reference__TypeAssignment_4");
					put(grammarAccess.getArtifactIDAccess().getManyAssignment_1(), "rule__ArtifactID__ManyAssignment_1");
					put(grammarAccess.getArtifactIDAccess().getNameAssignment_2(), "rule__ArtifactID__NameAssignment_2");
					put(grammarAccess.getArtifactIDAccess().getTypeAssignment_4(), "rule__ArtifactID__TypeAssignment_4");
					put(grammarAccess.getOnServiceAccess().getArtifactAssignment_0(), "rule__OnService__ArtifactAssignment_0");
					put(grammarAccess.getOnServiceAccess().getWhenServicesAssignment_2(), "rule__OnService__WhenServicesAssignment_2");
					put(grammarAccess.getOnServiceAccess().getWhenServicesAssignment_3_1(), "rule__OnService__WhenServicesAssignment_3_1");
					put(grammarAccess.getSimpleServiceAccess().getNameAssignment_2(), "rule__SimpleService__NameAssignment_2");
					put(grammarAccess.getSimpleServiceAccess().getInputAssignment_4_1(), "rule__SimpleService__InputAssignment_4_1");
					put(grammarAccess.getSimpleServiceAccess().getInputAssignment_4_2_1(), "rule__SimpleService__InputAssignment_4_2_1");
					put(grammarAccess.getSimpleServiceAccess().getOutputAssignment_5_1(), "rule__SimpleService__OutputAssignment_5_1");
					put(grammarAccess.getSimpleServiceAccess().getOutputAssignment_5_2_1(), "rule__SimpleService__OutputAssignment_5_2_1");
					put(grammarAccess.getSimpleServiceAccess().getWhenAssignment_6_1(), "rule__SimpleService__WhenAssignment_6_1");
					put(grammarAccess.getMultiServiceAccess().getNameAssignment_1(), "rule__MultiService__NameAssignment_1");
					put(grammarAccess.getMultiServiceAccess().getParallelAssignment_2_1(), "rule__MultiService__ParallelAssignment_2_1");
					put(grammarAccess.getMultiServiceAccess().getWhenAssignment_4_1(), "rule__MultiService__WhenAssignment_4_1");
					put(grammarAccess.getMultiServiceAccess().getServicesAssignment_6(), "rule__MultiService__ServicesAssignment_6");
					put(grammarAccess.getMultiServiceAccess().getServicesAssignment_7_1(), "rule__MultiService__ServicesAssignment_7_1");
					put(grammarAccess.getInoutAccess().getManyAssignment_0(), "rule__Inout__ManyAssignment_0");
					put(grammarAccess.getInoutAccess().getTypeAssignment_1(), "rule__Inout__TypeAssignment_1");
					put(grammarAccess.getInoutAccess().getCompatibilityAssignment_2_2(), "rule__Inout__CompatibilityAssignment_2_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			miso.distil.codeGenerator.ui.contentassist.antlr.internal.InternalRulesParser typedParser = (miso.distil.codeGenerator.ui.contentassist.antlr.internal.InternalRulesParser) parser;
			typedParser.entryRuleRoot();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RulesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RulesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
