/*
 * generated by Xtext
 */
package miso.carrascal.codeGenerator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RulesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("miso/carrascal/codeGenerator/parser/antlr/internal/InternalRules.tokens");
	}
}
